### ISSUE TITLE
SUGGESTION: PlaceholderAPI Support

### ISSUE THREAD

**Issue by slooshied** [flrping/Econoblocks#1]
It would be awesome to be able to see PlaceholderAPI Support in the Locale, simply so users could allow things like the player's new balance after the money has been added, etc. The possibilities are endless with PAPI!

[https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI)

**Comment by flrping** [comment]
Will be added in 2.0.0
